config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get 'search', to: 'search#index'

  resources :resources do
    get :download, on: :member
  end
  resources :categories

  namespace :admin do
    root to: 'categories#index'
  end

  root to: 'categories#index'
  devise_for :users, controllers: { sessions: 'admin/admin'}
end

app/views/resources/_form.html.slim
= simple_form_for(@resource) do |f|
  = f.error_notification

  - show_attributes = action_name == 'new' || action_name == 'create' || @resource.errors.present?

  .form-inputs
    = f.association :category, selected: params[:category] || @resource.category_id, label: t(:book_category)
  .form-inputs
    = f.input :name, label: t(:book_name)
  .form-inputs
    = f.input :description, as: :ckeditor, label: t(:book_description)
  .form-inputs
    = f.input :file, as: :file, label: t(:book_file)
    = button_tag t(:global_select), type: 'button', id: 'select_file'
    = link_to_blank @resource.file_file_name, @resource.file.url unless show_attributes
  .form-inputs
    = f.input :image, as: :file, label: t(:book_image)
    = button_tag t(:global_select), type: 'button', id: 'select_image'
    = image_tag @resource.image.url(:thumb) unless show_attributes

  .form-actions
    = f.button :submit, t(:global_save)

app/views/resources/edit.html.slim
h1 = t(:book_edit)

== render 'form'

= link_to t(:global_cancel), resource_path(@resource)

app/views/resources/index.html.slim
/h2 = t(:resource_list)

table
  thead
    tr
      th
      th
      - if @authenticated
        th
        th

  tbody
    - @resources.each.with_index(1) do |resource, index|
      tr
        td{style="vertical-align:top"}
          = "#{index}."
        td
          = link_to resource.name, resource_path(resource)
        - if @authenticated
          td = link_to t(:global_edit), edit_resource_path(resource)
          td = link_to t(:global_destroy), resource, data: {confirm: t(:global_destroy_sure, resource: resource.name)}, method: :delete

br

app/views/resources/new.html.slim
h1 = t(:book_new)

== render 'form'

= link_to t(:global_cancel), categories_path

app/views/resources/show.html.slim
p= link_to @resource.category.name, @resource.category
p= @resource.name
.clearfix.left.image
  = image_tag @resource.image.url(:medium)
.clearfix
  = @resource.description.html_safe
  - if @authenticated
    = link_to @resource.file_file_name, download_resource_path(@resource.id), target: '_self'
  - else
    .error= t(:book_authenticated)
br
- if @authenticated
  - if @resource.file_content_type == 'application/pdf'
    .clearfix
      iframe src="http://#{ ENV['DOMAIN_NAME'] }/pdfjs-dist/viewer.html?file=#{ download_resource_path(@resource.id) }" width="100%" height="600px"

  - if current_user.admin?
    = link_to t(:global_edit, resource: t(:book_new)), edit_resource_path(@resource)
    '&nbsp;|
    = link_to t(:global_cancel), categories_path