config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get 'search', to: 'search#index'

  resources :resources do
    get :download, on: :member
  end
  resources :categories

  namespace :admin do
    root to: 'categories#index'
  end

  root to: 'categories#index'
  devise_for :users, controllers: { sessions: 'admin/admin'}
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :resources, -> { order 'name asc' }, inverse_of: :category, dependent: :destroy

  validates :name, presence: true, uniqueness: {case_sensitive: false}

  include Searchable

  settings do
    mappings do
      indexes :id, type: 'integer', index: 'not_analyzed'
      indexes :name, type: 'keyword'
      indexes :description, analyzer: 'snowball'
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  after_action :verify_authorized, except: [:index, :show]
  after_action :verify_policy_scoped, only: :index

  # GET /categories
  # GET /categories.json
  def index
    @categories = policy_scope(Category.order :name)

    @authenticated = user_signed_in? && current_user.admin?
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @resources = @category.resources

    @authenticated = user_signed_in? && current_user.admin?
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize @category
  end

  # GET /categories/1/edit
  def edit
    authorize @category
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    authorize @category

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: t(:category_created) }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    authorize @category

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: t(:category_updated) }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    authorize @category

    respond_to do |format|
      format.html { redirect_to categories_url, notice: t(:category_destroyed) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, label: t(:category_name)
  .form-inputs
    = f.input :description, as: :ckeditor, label: t(:category_description)

  .form-actions
    = f.button :submit, t(:global_save)

app/views/categories/edit.html.slim
h1 = t(:category_edit)

== render 'form'

= link_to t(:global_cancel), categories_path

app/views/categories/index.html.slim
h1 = t(:category_list)

- if @authenticated
  p= link_to t(:category_new), new_category_path

table
  thead
    tr
      th
      - if @authenticated
        th
        th

  tbody
    - @categories.each do |category|
      tr
        td = link_to category.name, category
        - if @authenticated
          td = link_to t(:global_edit), edit_category_path(category)
          td = link_to t(:global_destroy), category, data: {confirm: t(:global_destroy_sure, resource: category.name)}, method: :delete

- if @authenticated
  p= link_to t(:category_new), new_category_path

app/views/categories/new.html.slim
h1 = t(:category_new)

== render 'form'

= link_to t(:global_cancel), categories_path

app/views/categories/show.html.slim
- if @authenticated
  p= link_to @category.name, edit_category_path(@category)
  = link_to t(:global_new, resource: t(:book_new)), new_resource_path(category: @category.id)
  '&nbsp;|
  = link_to t(:global_cancel), categories_path
- else
  p= @category.name
p= @category.description.html_safe

- if @resources.length > 0
  = render template: 'resources/index'

- if @authenticated
  = link_to t(:global_new, resource: t(:book_new)), new_resource_path(category: @category.id)
  '&nbsp;|
  = link_to t(:global_cancel), categories_path