config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get 'search', to: 'search#index'

  resources :resources do
    get :download, on: :member
  end
  resources :categories

  namespace :admin do
    root to: 'categories#index'
  end

  root to: 'categories#index'
  devise_for :users, controllers: { sessions: 'admin/admin'}
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :class => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
    <li class="right"><%#= link_to 'Edit account', edit_user_registration_path %></li>
    <li class="right"><%= link_to t(:sign_out), destroy_user_session_path, :method => 'delete' %></li>
<% else %>
    <li class="right"><%= link_to t(:sign_in), new_user_session_path %></li>
    <li class="right"><%#= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.slim
ul.nav
  /li
  /  = link_to t(:app), user_signed_in? ? admin_root_path : root_path
  li
    = link_to t(:category_list), categories_path
  == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%= render partial: 'layouts/nav_links_for_auth' %>

app/views/layouts/_sidebar.html.slim
#sidebar
  = image_tag 'adi-logo.png', id: 'logo', alt: '', title: ''
  h1= t :app

  = form_tag search_path, method: 'get' do
    = text_field_tag :query, params[:query], autofocus: true, tabindex: 0
    = submit_tag t(:search), :name => nil

  p.font.tip= t(:search_tip).html_safe

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title= content_for?(:title) ? yield(:title) : t(:app)
    meta name="description" content="#{content_for?(:description) ? yield(:description) : t(:app)}"
    == javascript_tag 'window.locale = ' << I18n.locale.to_s.inspect
    == csrf_meta_tags
    == favicon_link_tag 'adi-icon.png', type: 'image/png'
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == javascript_include_tag user_signed_in? ? 'admin' : 'reader', 'data-turbolinks-track' => true
  body
    header
      == render 'layouts/navigation'
    main[role="main" id="wrap"]
      == render 'layouts/sidebar'
      #content
        == render 'layouts/messages'
        == yield
    footer